// export const PRODUCT_SERVICE = "PRODUCT_SERVICE";
// export const ORDER_SERVICE = "ORDER_SERVICE";
export enum SERVICES {
  PRODUCT_SERVICE = 'PRODUCT_SERVICE',
  ORDER_SERVICE = 'ORDER_SERVICE',

  NATS_SERVICE = 'NATS_SERVICE',
}
